### ISSUE TITLE
Component not being loaded on Cloud Run

### ISSUE THREAD

**Issue by andreasntr** [thunderbug1/streamlit-javascript#15]
When deploying an app on Google Cloud Run, the following error shows when executing any `st_javascript` script.
Using Streamlit Community Cloud or localhost, the app works without problems.

`st_javascript` call:

`st_javascript('''[window.innerWidth, parent.window.innerHeight];''', key=...)`

Dokerfile:

```
#Base Image to use
FROM python:3.10-slim

#Expose port 8080
EXPOSE 8080

#Copy Requirements.txt file into app directory
COPY requirements.txt app/requirements.txt

#install all requirements in requirements.txt
RUN python -m pip install --upgrade pip && pip install -r app/requirements.txt

#Copy all files in current directory into app directory
COPY . /app

#Change Working Directory to app directory
WORKDIR /app

#Run the application on port 8080
ENTRYPOINT ["streamlit", "run", "app.py", \
  "--server.port=8080", \
  "--client.showErrorDetails=false", \
  "--client.toolbarMode=viewer"]
```

**Comment by andreasntr** [comment]
Closing, seems like a Cloud Run issue with JS components. Also happens with similar components

**Comment by Strings-RH** [comment]
If someone finds this post and is looking for a fix.
Setting browser.serverAddress might be the solution, looking at its documentation: lib/streamlit/config.py Line 850

The other bit of code which seems very focused on running on the streamlit community cloud can be found in lib/streamlit/web/server/routes.py Line 200, which seems to limit routing messages. I am not sure if setting serverAddress is enough to bypass this routing.

If you can catch my attention, I am disabled and am not always available for months at a time, I would be happy to investigate this with somebody who has an issue running js in the browser on any platform.
