### ISSUE TITLE
Purpose of bootstrap.min.css?

### ISSUE THREAD

**Issue by Timmate** [thunderbug1/streamlit-javascript#16]
Apologies for a probably dumb question, but what is the purpose of bootstrap.min.css? I mean, if it's just sort of a fake component, what is then such a long CSS for? Thanks in advance!

**Comment by Timmate** [comment]
Apparently, this is a Bootstrap thing necessary for making the whole thing work. Can't seem to delete the issue, so I'm closing it.

**Comment by Strings-RH** [comment]
I have removed this in PR #19 without any problems.
