### ISSUE TITLE
Does this run the JS serverside or client side?

### ISSUE THREAD

**Issue by dxk5271** [thunderbug1/streamlit-javascript#17]
Does this run the JS server side or client side?

**Comment by avocado-beans** [comment]
Same question here.

**Comment by avocado-beans** [comment]
![image](https://github.com/user-attachments/assets/93ca9157-4e28-4a7f-9278-5b52e01b9b79)
looks like it's client side

**Comment by dxk5271** [comment]
Thanks. Yes confirmed it's client side for sure.

**Comment by thunderbug1** [comment]
Yes it does run client side, that was actually the whole motivation since I had to do an API call with the auth cookie of the client and didn't know how. That's why I made the package.
